### ISSUE TITLE
How the line semantic segmentation labels generated?

### ISSUE THREAD

**Issue by WellYoungIOE** [SoccerNet/sn-calibration#1]
Hi, great works for sports camera calibration.

I have tried your provided baseline for soccer pitch elements localization. The semantic segmentation results of "src/baseline_extremities.py" seem very coarse. And the semantic labels of junction pixels seem well defined. It makes me curious about the way you generate the line semantic segmentation labels for soccer pitch elements. 

Did you dilate the connecting line of coordinate pairs in the label JSON file?  If so, did you dilate the connecting lines with a fixed value?
And how do you define the semantic label for the junction pixels?

Thanks!

![image](https://user-images.githubusercontent.com/19660081/154062593-680c7b57-95e7-4695-9522-7e6d93216480.png)

**Comment by fmagera** [comment]
Hello, 
Thanks for your interest !
The semantic masks are generated using the code in the dataloader.py file. We basically draw a 2-pixels wide line between the extremities of each soccer pitch element. There is no specific treatment for the intersection of the lines, if two lines overlap, then the last one drawn overwrites the other. A more clever handling of these might give better results.

I hope this answers your questions ! 

Best,
Floriane
