### ISSUE TITLE
Bug in evaluate_extremities.py

### ISSUE THREAD

**Issue by jhbrito** [SoccerNet/sn-calibration#19]
Hi.
I believe I found a bug in the evaluation script for the extremities, evaluate_extremities.py

Function evaluate_detection_prediction is defined as
def evaluate_detection_prediction(groundtruth_lines, detected_lines, threshold=2.):

However, it is called in lines 192 and 195 with incorrectly ordered parameters
confusion1, per_class_conf1, reproj_errors1 = evaluate_detection_prediction(img_prediction, img_groundtruth, args.threshold)

It is also called in evalai_extremities.py with reversed parameters:
confusion1, per_class_conf1, reproj_errors1 = evaluate_detection_prediction(img_prediction, img_groundtruth, 10)

Since, the metrics are based on geometric distances between predictions and groundtruth, this probably does not have an impact on the evaluation if all classes are detected by the predictor.
If however the predictor fails to detect some classes of lines and the prediction is treated as groundtruth, the metrics will yield false positives instead of false negatives.

I would suggest simply swapping the parameter order on the function definition for a quicker fix.

Cheers
Jose

**Comment by fmagera** [comment]
Hi Jose ! 
Thanks for spotting that ! It is fixed :)
