### ISSUE TITLE
where can I get the common 3D pitch template?

### ISSUE THREAD

**Issue by XinyingWang55** [SoccerNet/sn-calibration#2]
where can I get the common 3D pitch template?

**Comment by WellYoungIOE** [comment]
> where can I get the common 3D pitch template?

It is in the soccerpitch.py.
https://github.com/SoccerNet/sn-calibration/blob/b7f56594ea40ca55a8bbfa7a9e11b4b54414c9f3/src/soccerpitch.py#L109
