### ISSUE TITLE
Inout / output calibration

### ISSUE THREAD

**Issue by Tortoise17** [SoccerNet/sn-calibration#21]
I have to ask two question. For the input together with bounding boxes, colors are also important? or without colors system can take input? also, 

the input requirements are hemography and bounding boxes. What we get as output? Labels-cameras.json? For that case, how to export it with the Calf calibration for next step replay grounding? Or Calf calibration also exports labels-v2.json ? Please correct me if I am wrong. and pleae guide me for some possible hints to understand the workflow.

**Comment by fmagera** [comment]
Hi Tortoise17 ! 
It seems you landed on the wrong repository? You seem interested in our previous works : https://github.com/evs-broadcast/CCBV that was used for the CALF_calibration baseline with top view generation.

**Comment by Tortoise17** [comment]
@fmagera No, actually, The task 1 is action spotting. From inference of that, we get the labels-v2.json like that. and I want to get to the point where we can get the replay grounding. So, to reach that point which part or pipeline I am misunderstanding I am trying to figure out. If you can help me.

**Comment by fmagera** [comment]
So maybe you want to look at the repository on replay-grounding ? https://github.com/SoccerNet/sn-grounding 
This repo is standalone and there is no links with other tasks.

**Comment by Tortoise17** [comment]
Yes, but for inference, what input is required to get the output? I think without the calibration it is not possible or it is dependent on that?

**Comment by SilvioGiancola** [comment]
Hi @Tortoise17 

This repository is not for spotting nor grounding, but for camera calibration and field localization. If you have an issue with the player localization, you won't find any answer here.

Can you please explain your issue in:
 - [sn-spotting](https://github.com/SoccerNet/sn-spotting/issues) if it is related to the spotting baselines.
 - [sn-grounding](https://github.com/SoccerNet/sn-grounding/issues) if it is related to the grounding baselines.

Thank you!
