### ISSUE TITLE
How to calculate Homography Matrix from annotations?

### ISSUE THREAD

**Issue by AtomScott** [SoccerNet/sn-calibration#22]
Is there a way to calculate the Homography Matrix between the template pitch and an annotated frame? 
I haven't been able to do this since the annotations were line segments and not points.

**Comment by fmagera** [comment]
Hi @AtomScott, sure there is ! You can compute an homography from line correspondences too :)  It is exactly what is being done there: https://github.com/SoccerNet/sn-calibration/blob/ff1012c4b10f7a167f4975d48197804a5cc834ea/src/baseline_cameras.py#L44

**Comment by AtomScott** [comment]
Thanks, I was able use this function to calculate the homography!
