### ISSUE TITLE
sn-calibration dataset camera

### ISSUE THREAD

**Issue by mauroan** [SoccerNet/sn-calibration#23]
Is there a per-frame annotation of the camera type for each frame in this dataset (e.g. frame `train/00000.jpg` -> `Main camera center`)? I am asking because it may be useful to identify frames that are from a camera behind the goalkeeper since in that case we cannot differentiate between left and right goal. Thanks.

**Comment by fmagera** [comment]
Hi @mauroan, 
No there is no such annotation. We are aware of this ambiguity and this is why we account for it in the evaluation procedure.

**Comment by mauroan** [comment]
thanks @fmagera, I thought it was possible to extract these labels from the [Labels-cameras.json](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Download) that you can download for each match. 

Unfortunately the timestamp for each frame in the calibration dataset (the `ms_time` you can find for each frame in  `match_info.json`) doesn't represent the time of the frame in the game (not sure what it represents). Maybe you have the correct timestamp information somewhere and  `match_info.json` can be updated?

Another option is to use an OCR to read the time directly from the frame and then use it to extract the annotated camera from `Labels-cameras.json`.

**Comment by fmagera** [comment]
You're refereeing to the annotations of the replay grounding task, I am afraid I am not very familiar with those. Maybe @cioppaanthony can help us with that?

**Comment by cioppaanthony** [comment]
Hi @mauroan,

The information for the camera class is only present for 200 out of the 500 broadcast games, and hence won't be available for all images in the camera calibration dataset. Regarding the timestamp format for the camera type you can check out this explanation, it is the same as for replay grounding: https://youtu.be/n-fWUr2SKqQ?t=2278.
Basically it is a timestamp pointing to the end of a clip (so you have to look at the previous timestamp to have the start.)

Note that the timestamps are only valid for the video named {1,2}_720p.mp4 or {1,2}_240p.mp4.

Are you sure you are using those videos and not the {1,2}_HQ.mkv ones (which are not synced with the annotations) ?

**Comment by mauroan** [comment]
thanks @cioppaanthony, I didn't noticed it is present only for 200 games, thanks for pointing that out.

Regarding the timestamp that are not correct I was referring to the one that can be found in `match_info.json` in the **sn-calibration dataset**. If you open that file you can see that the value for `ms_time` is the same for all the frames with the same `event_id` and it seems to be incorrect for all of them except the first one, for example:

   

>  "00001.jpg": {
>         "league": "england_epl",
>         "season": "2014-2015",
>         "match": " Burnley - Arsenal",
>         "date": "15-04-11",
>         "event_id": "1",
>         "ms_time": 69643,
>         "half": 1
>     },
>     "00002.jpg": {
>         "league": "england_epl",
>         "season": "2014-2015",
>         "match": " Burnley - Arsenal",
>         "date": "15-04-11",
>         "event_id": "2",
>         "ms_time": 69643,
>         "half": 1
>     },

`00001.jpg` and `00002.jpg` are two different frames in the sn-calibration dataset but they have the same value for the attribute `ms_time`. This value is correct for the first frame 1:09 but is wrong for the second one (it should be 78000 -> 1:18 looking at the image).

**Comment by fmagera** [comment]
Hi @mauroan, thanks for pointing that out !

**Comment by fmagera** [comment]
This will be corrected in the next version of the challenge. The idea is to enable participants to leverage multi-view calibration, by keeping the time code in ms of the event, and attributing it to the linked replays of said event. There is definitely something wrong: in your example the event_id should be the same because the frames are clearly showing the same event at the same moment, from a different camera angle. 
You can't trust the timer added in the image : when there is a replay, the timer continues to augment as the game is still going on (even if broadcasters are showing you images from the past : timer does not go back in time). 
In the next version,  event_id will be corrected and will definitely add the replay timecode in order to ensure you can find it from the video.  
I hope this helps you for now !

**Comment by mauroan** [comment]
Thanks @fmagera, I hadn't noticed before they were referring to the same image from different angles. Now the data makes a lot more sense to me. Looking forward to the next version of the challenge, keep up the good work!
