### ISSUE TITLE
Possible typo 

### ISSUE THREAD

**Issue by stakas** [SoccerNet/sn-calibration#24]
I am scratching my head on these few lines:

https://github.com/SoccerNet/sn-calibration/blob/1dedcabf6db29f7d57f8bd32d7c84312ce6438b7/src/camera.py#L131

If lambdas are taken from Zhang's paper "[A Flexible New Technique for Camera Calibration](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf)" then it must read: `r0 = hprim[:, 0] * lambda1` and *not* `r0 = hprim[:, 0] / lambda1`. I think there must have been a confusion since lambdas in "Real time camera pose estimation for sports fields" are actually 1 over lambdas in Zhang's paper. In any case, probably fixing this would result in a better refinement with LM thereafter.

**Comment by fmagera** [comment]
Hi @stakas, 
Yes you're right, thanks ! :)
