### ISSUE TITLE
Aspect ration may be generalized

### ISSUE THREAD

**Issue by stakas** [SoccerNet/sn-calibration#25]
This line sets restrictions on  matrix `A` coefficients, but this restriction is valid only for cameras with 16:9 aspect ratio. I think it can be generalized to: `A[2, 3] = self.principal_point[1] / self.principal_point[0]`
https://github.com/SoccerNet/sn-calibration/blob/9f9f6b30d4074654703ec5fa4c2b4c8537fee052/src/camera.py#L354

**Comment by fmagera** [comment]
Yes, indeed! If you want, you can make pull requests :)
