### ISSUE TITLE
Submission on EvalAI failing

### ISSUE THREAD

**Issue by stakas** [SoccerNet/sn-calibration#29]
Hi, @fmagera I can't seem to be able to submit camera predictions for Test dataset on EvalAI even though locally it works fine - reverse engineering StdErr, it seems that submissions are marked as "missing". Since we can't see what are folder and file names on your machine to which predictions are being matched to, can it be some sort of typo in folder names? Specifically, it seems that zipped file is named "test_secret" on your machine, which would imply that zipped folder is also named "test_secret" and it is being matched to folder named "test"...?

https://github.com/SoccerNet/sn-calibration/blob/0350c24a269853628cfa8d60f532e3ae77f15367/src/evalai_camera.py#L29

Anyways, some help would be appreciated  :)

**Comment by fmagera** [comment]
Hello @stakas, 
What is the structure of your zip file ? It should be something like : 
test.zip
|- camera_00001.json
|- camera_00002.json
|_camera_....json

**Comment by stakas** [comment]
I am zipping  below test folder with `zip -r test.zip test`
<img width="1183" alt="Screenshot 2023-04-06 at 14 42 40" src="https://user-images.githubusercontent.com/8689905/230366860-5bba2bf5-0273-47be-8dd0-bf20b1b8ccdb.png">

**Comment by fmagera** [comment]
Ok that's the problem, zip directly the files, not the folder. The readme is not up to date on that matter, sorry for the inconvenience !

**Comment by stakas** [comment]
ah ok, gotch, thanks!
