### ISSUE TITLE
Which one is the dataset for final evaluation of the competition? The "Test" or the "Challenge"?

### ISSUE THREAD

**Issue by WellYoungIOE** [SoccerNet/sn-calibration#3]
Hi,

It is a question about the competition.

We found that there are two phases for each track on the competition page (https://eval.ai/web/challenges/challenge-page/1537/phases), the "Test" phase, and the "Challenge" phase. This makes us a little confused that which one is used for the final evaluation, or they are both used for the final evaluation?

Thanks!

**Comment by fmagera** [comment]
Hi, 

The test set comes with the ground-truth annotations for the community and can be used for benchmarking on scientific paper (evaluated locally on anyone's machine). 

The challenge set has private ground-truth and performances can only be evaluated on our evaluation server with limited amount of daily and monthly submissions. The challenge leaderboard will be kept private until the end of the challenge. It is only the challenge performance that will be used to rank participants at the end of the challenge (at the end of May). 

You can submit on both, but for the test set it's not mandatory.

I hope this is clearer !
