### ISSUE TITLE
ERROR Unknown task: calibration-2023

### ISSUE THREAD

**Issue by pulism** [SoccerNet/sn-calibration#30]
``` python
downloader = SoccerNetDownloader(LocalDirectory="zipped_images_new")
downloader.downloadDataTask(task="calibration-2023", split=["train","valid","test","challenge"])
```

This code returns the following error:
```
ERROR Unknown task: calibration-2023
```

Am I doing something incorrectly? Also, this 2023 version contains all the images that were there before, or does it only contain new images, or something else?

Thanks :)

**Comment by SilvioGiancola** [comment]
Do you have the latest version of the SoccerNet pip package? `pip install SoccerNet --upgrade`

**Comment by pulism** [comment]
Ok, the command you provided worked. Note for anyone that tries this and finds that the error still shows up and is using a Jupyter Notebook, don't forget to restart the kernel after running the upgrade!

Thanks @SilvioGiancola :)
