### ISSUE TITLE
Circle annotations are sometimes in the wrong order.

### ISSUE THREAD

**Issue by pulism** [SoccerNet/sn-calibration#31]
Consider this case, where I am visualising the line annotations:

<img width="571" alt="image" src="https://github.com/SoccerNet/sn-calibration/assets/121873204/d1d93b22-eb47-4c42-8ad8-0cf4ce576aef">

This is the output of the same code on different a annotation:

<img width="562" alt="image" src="https://github.com/SoccerNet/sn-calibration/assets/121873204/c1ad4197-74f0-4c39-a9f3-0a6a8e8b49ab">

The majority of cases produce output where the circle is drawn correctly. The drawing is done by plotting a line between sequential points of the circle. This strange error is also true for both the left and right penalty box circles. Empirically I would say the split of correctly annotated:incorrectly annotated circles seems to be like 4:1.

This is unless I am drawing them incorrectly, and my assumption that circles are defined by sequential points only is incorrect, however considering that they are defined this way in most cases I would be confused as to how this would be the case.

**Comment by fmagera** [comment]
Hi @pulism, 
Thanks for pointing that out ! We've added some annotations lately, and it is possible that in this process, sequential order of the annotation was lost. For these you can only assume that the annotated points belong to a circle, not that it is in a sequential order. This does not have any impact on the evaluation procedure, so apart the need to adapt your drawing function and sort the points first, there should not be any problem with that.

**Comment by pulism** [comment]
Got it, thanks :)
