### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by compmind-nishihata** [SoccerNet/sn-calibration#32]
Hi, I ran the code from README.md's All the data needed for challenge can be downloaded with these lines  and tried to download it.
Calibration-2023(task="calibration-2023") failed to download with HTTP Error 404: Not Found.
How can I download task="calibration-2023"?

**Comment by fmagera** [comment]
Hi, 
The server hosting the datasets is currently under maintenance. Sorry for the inconvenience and thank you for your patience !

**Comment by SilvioGiancola** [comment]
Hi, 

Sorry about that error, the download links have changed this week. 

Please update the pip package to its latest version, v0.1.53 (pip install SoccerNet --upgrade), try again, and let me know if that works for you.

Best,

**Comment by a-pru** [comment]
Hi,

Unfortunately, downloading also fails using the latest version of the pip package.

Best,
Alex

**Comment by SilvioGiancola** [comment]
This is a different issue, it was working until a few hours ago. We are experiencing some connection issues at our university, please bear with us.

**Comment by a-pru** [comment]
Thank you very much for the quick response!

**Comment by SilvioGiancola** [comment]
Our server is back online. Please give it a try now.
