### ISSUE TITLE
Guidance on Transforming Extracted Lines to a Top-Down View Using Camera Parameters

### ISSUE THREAD

**Issue by Hmiru** [SoccerNet/sn-calibration#35]
Hello, I've used this repository to extract camera parameters and detect lines from a challenge dataset.

My goal is to transform these into a top-down view, where players are represented as markers based on their positions on the field.

While I understand that object detection is necessary to locate the players, I'm uncertain about the process of converting the current view into a top-down perspective using the extracted lines and camera parameters. 

Specifically, I'm looking for advice on how to use the camera.py (or any relevant) module to achieve this transformation.

Could you provide guidance or examples on how to proceed with creating a top-down view representation of the game using the available camera parameters and the detected lines? 

Any help or pointers to resources that could assist me in this task would be greatly appreciated.Thank you for your time and assistance.

**Comment by fmagera** [comment]
Hi, 

I am not sure I totally get what you are trying to do. A top-down view is an image that can be created from 3D information that is the soccer pitch model and the players positions. As the soccer pitch model is known, I would not use the line detection info for drawing the pitch. 

First, you need the players 3D positions : by detecting them in an image that is calibrated, you can derive that.
Do you estimate radial distortion in your camera calibration? If not, you can convert your camera parameters to a homography : ```
H = camera.calibration @ camera.rotation @ np.concatenate((np.eye(3)[:, :2], -camera.position.reshape(3, 1)),
                                                                 axis=1)
```
Then use the `unproject_image_point` function from camera.py to get a 3D point from a 2D image point (that would be the 2D detection of the players feet in your case). 

Then, having both your 3D players feet position and the soccer pitch model given in the soccerpitch.py file, you can draw a top-view representation. To draw the soccer pitch, you can use the [draw_pitch_homography](https://github.com/SoccerNet/sn-calibration/blob/main/src/baseline_cameras.py#L109) function, and a homography that produces the desired kind of top-down projection. For instance, for a (960, 540) top-down image, I could use the following code snippet
```
f = 6
w = 960, h = 540
black_img = np.zeros((h, w, 3))
top_view_h = np.array([[f, 0, w/2], [0, f, h/2], [0, 0, 1]])
draw_pitch_homography(black_img, top_view_h)
```
Finally, for each player, you need to compute the image of their feet with the same homography: 
```
imaged_feet = top_view_h @ np.array([feet[0], feet[1], 1])
imaged_feets /= imaged_feets[2]
color = (153, 255, 255)
cv.circle(black_img, (int(imaged_feets[0]), int(imaged_feets[1])), 2, color, -1)
```
I hope this helps !

**Comment by Hmiru** [comment]
![00000](https://github.com/SoccerNet/sn-calibration/assets/46088502/da8fb4e4-e677-4b33-9a42-63457eb651e9)
Thank you for your kind reply. However, I've encountered another issue regarding determining point coordinates. I'm attempting to convert the goalkeeper's position into a top view. His coordinates in the provided image are (543, 237), so I set the parameter of unproject_image_point like this: `feet = pitch_point = unproject_image_point(H, point2D=[543, 237, 1])` However, the output I get seems incorrect, as shown in the image below: 
![image](https://github.com/SoccerNet/sn-calibration/assets/46088502/6ad7cafd-3b5f-49d1-8392-03201b42e74c)
How should I properly set the coordinates for calibration? Thanks in advance for your assistance.
```
camera.from_json_parameters(calib_json_object)
H = camera.calibration @ camera.rotation @ np.concatenate((np.eye(3)[:, :2], -camera.position.reshape(3, 1)), axis=1)
feet=pitch_point=unproject_image_point(H,point2D=[540, -36,1])
# which is
f = 6
w = 960
h = 540

black_img = np.zeros((h, w, 3), dtype=np.uint8)
top_view_h = np.array([[f, 0, w/2], [0, f, h/2], [0, 0, 1]])
draw_pitch_homography(black_img, top_view_h)

imaged_feets = top_view_h @ np.array([feet[0], feet[1], 1])
imaged_feets /= imaged_feets[2]
color = (153, 255, 255)

cv.circle(black_img, (int(imaged_feets[0]), int(imaged_feets[1])), 12, color, -1)
plt.imshow(cv.cvtColor(black_img, cv.COLOR_BGR2RGB)) 
plt.axis('off') 
plt.show()
```

**Comment by Hmiru** [comment]
Hello!

Here are the camera parameters.
```
{
    "pan_degrees": 15.874998370169184,
    "tilt_degrees": 54.51312901467806,
    "roll_degrees": 10.687066257473708,
    "position_meters": [
        27.317666040655087,
        74.33004848464584,
        -37.30766279820353
    ],
    "x_focal_length": 1749.6261535496722,
    "y_focal_length": 1749.626153549676,
    "principal_point": [
        480.0,
        270.0
    ],
    "radial_distortion": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
    ],
    "tangential_distortion": [
        0.0,
        0.0
    ],
    "thin_prism_distortion": [
        0.0,
        0.0,
        0.0,
        0.0
    ]
}
```
Does the value of feet represent the 3D point calculated by the unproject_image_point function? If so, it is calculated as follows:
`feet=pitch_point=unproject_image_point(H,point2D=[543, 237,1])`
`feet=[44.44084587 23.40823608  1.        ]`

**Comment by fmagera** [comment]
From what I see, the camera parameters are not quite precise. If you draw the soccer pitch in the image, you will visualize the quality of the camera parameters. 
I guess the function draw_pitch_homography with H and your input image will produce something ugly.

**Comment by Hmiru** [comment]
Oh..Ok. it is raw version of Draw_pitch_homography function. But do i need to modify to get a clean result, right? By the way the approach to setting the 2D point as a parameter is correct, with the bottom left corner as (0,0)?

**Comment by fmagera** [comment]
At this point, the functions and your use of them are fine, the camera parameters are wrong. Maybe you could try other methods to estimate them? This repo just provides a baseline, but participants to the previous challenges have published their code :)
