### ISSUE TITLE
submit file but the precision is 0

### ISSUE THREAD

**Issue by Channingss** [SoccerNet/sn-calibration#4]
I submitted the following file which generated by ground truth, but the precision is 0. Could you please help me to confirm what is wrong?
[test.zip](https://github.com/SoccerNet/sn-calibration/files/8195660/test.zip)

**Comment by cioppaanthony** [comment]
Hi @Channingss,

It could be that it is because your zip file is organized as: "test.zip/test/*.json" while it should be "test.zip/*.json".

Could you please try that and tell me if it works?
If that's the issue, we will update the README to specify this more precisely.

Thanks in advance,

**Comment by Channingss** [comment]
> 
you described problem is true.  

Another question, the leader board will test  the challenge dataset, but why do you provide the json(ground truth) of the challenge?

**Comment by SilvioGiancola** [comment]
Hi @Channingss we won't share the ground truth of the challenge set.
