### ISSUE TITLE
can track 1 use 3d  field template?

### ISSUE THREAD

**Issue by Channingss** [SoccerNet/sn-calibration#6]
can track 1 use field template info as input to predict? such as field coordinate info and so on.

https://github.com/SoccerNet/sn-calibration/blob/b7f56594ea40ca55a8bbfa7a9e11b4b54414c9f3/src/soccerpitch.py#L4

**Comment by Channingss** [comment]
hi, can anybody give an answer , which  wuill affect our solutions.

**Comment by fmagera** [comment]
Hi, 

Yes sure, you can use the 3D pitch template described in the soccerpitch.py file.
