### ISSUE TITLE
Is there a code that generates eval server results?

### ISSUE THREAD

**Issue by mazatov** [SoccerNet/sn-calibration#7]
I've successfully submitted the results from your benchmark code and was able to get the exact same baseline results(surprise!) :) However I was wondering if there is a code that's running behind eval.ai somewhere. The `eval_extremities.py` doesn't seem to print out the same values. It would be nice to have this code so I can get the results for test dataset and not have to submit results every time I do a little change.

**Comment by SilvioGiancola** [comment]
Hi @mazatov , the code running on eval.ai is available on the SoccerNet package, if we have not advertised it (yet), then our bad!

Basically, we have 2 evaluation functions for the 2 tasks in the calibration challenge, that you can access with:

```
from SoccerNet.Evaluation.FieldCalibration import evaluate as evaluate_field
from SoccerNet.Evaluation.CameraCalibration import evaluate as evaluate_camera

results_field = evaluate_field(GT_zipped, submission_zipped, threshold=5)
Accuracy_5 = results_field["meanAccuracies"]*100

results_camera = evaluate_camera(GT_zipped, submission_zipped, threshold=5)
Completeness = results_camera["completeness"]*100
Accuracy_5 = results_camera["meanAccuracies"]*100
```
You will have to provide the GT for each split, but we do not release the GT for the challenge set. Of course you can play with the threshold in both task to get the results at different thresholds.

@fmagera it looks like @mazatov is getting different results than when using your functions developed here: https://github.com/SoccerNet/sn-calibration/blob/b7f56594ea40ca55a8bbfa7a9e11b4b54414c9f3/src/evalai_camera.py#L10

Any idea why, have you experienced a similar discrepancy?

Cheers,

**Comment by fmagera** [comment]
Hi, 

It seems really strange as the evalai_extremities.py should be exactly the code that is used for the evaluation server. Can you provide more details ?

**Comment by fmagera** [comment]
After a quick test, I get exactly the same results but indeed, the evalai_extremities.py and the package function expect zip files organized differently... Could that explain the difference you've noticed ? If so, we will just change that in the repo !

**Comment by mazatov** [comment]
@fmagera , I noticed about the different zip structures so I adjusted for that. Another thing I missed was that `evalai_extremities.py` is set to use `threshold = 10`. I didn't realize that was fixed there.

**Comment by mazatov** [comment]
With those two changes, I think I get the same results!

**Comment by SilvioGiancola** [comment]
Great, I am glad it was simply a mistake in the code, and that indeed the results in both this repo and the pip package (hence eval.ai) are similar.
Cheers!
