### ISSUE TITLE
Which metric do you use for the final evaluation?

### ISSUE THREAD

**Issue by WellYoungIOE** [SoccerNet/sn-calibration#8]
Hi,

There are three metrics acc@5, acc@10, and acc@20 for evaluation in the challenge.

I am wondering which one will be used for the final evaluation. 

Or you will average them as the final results?

Thanks!

**Comment by fmagera** [comment]
Hi, 

We will communicate soon the final details of the evaluation. For the pitch localization, it will indeed be based on these metrics only and for the camera calibration, we will include the completeness rate somehow in the final score.

**Comment by WellYoungIOE** [comment]
> Hi,
> 
> We will communicate soon the final details of the evaluation. For the pitch localization, it will indeed be based on these metrics only and for the camera calibration, we will include the completeness rate somehow in the final score.

OK, looking forward for you conclusion.
